
name: Assign Reviewer for Dependabot PRs

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'dependencies' )


    steps:
      - name: Assign reviewer action
        uses: ilyaulyanov/action-assign-random-reviewer@v1.9.4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
